max_width = 120
newline_style = "Unix"
fn_args_layout = "Tall"
use_small_heuristics = "Max"
use_field_init_shorthand = true
use_try_shorthand = true

# Unstable args
unstable_features = true
group_imports = "One"
